spring:
#  jpa:
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create
      
  datasource:
     url: jdbc:mysql://localhost:3306/delivery?serverTimezone=UTC
     username: root
     password: root